#!/usr/bin/env python3
"""Interactive credential setup wizard for MJAS v3.0."""

import getpass
import os
from pathlib import Path


def main():
    print("MJAS v3.0 - Credential Setup Wizard")
    print("=" * 50)
    print()

    # Get email (use same across platforms for simplicity)
    print("Using the same email for all platforms is recommended.")
    email = input("Your email address: ").strip()
    print()

    credentials = {"GMAIL_EMAIL": email}

    # LinkedIn
    print("--- LinkedIn ---")
    credentials["LINKEDIN_EMAIL"] = input(f"LinkedIn email [{email}]: ").strip() or email
    credentials["LINKEDIN_PASSWORD"] = getpass.getpass("LinkedIn password: ")
    print()

    # Indeed
    print("--- Indeed ---")
    credentials["INDEED_EMAIL"] = input(f"Indeed email [{email}]: ").strip() or email
    credentials["INDEED_PASSWORD"] = getpass.getpass("Indeed password: ")
    print()

    # Wellfound
    print("--- Wellfound (AngelList) ---")
    credentials["WELLFOUND_EMAIL"] = input(f"Wellfound email [{email}]: ").strip() or email
    credentials["WELLFOUND_PASSWORD"] = getpass.getpass("Wellfound password: ")
    print()

    # Naukri
    print("--- Naukri (India) ---")
    credentials["NAUKRI_EMAIL"] = input(f"Naukri email [{email}]: ").strip() or email
    credentials["NAUKRI_PASSWORD"] = getpass.getpass("Naukri password: ")
    print()

    # Glassdoor (optional)
    print("--- Glassdoor (optional) ---")
    gd_email = input(f"Glassdoor email [press Enter to skip]: ").strip()
    if gd_email:
        credentials["GLASSDOOR_EMAIL"] = gd_email
        credentials["GLASSDOOR_PASSWORD"] = getpass.getpass("Glassdoor password: ")
    print()

    # ZipRecruiter (optional)
    print("--- ZipRecruiter (optional) ---")
    zr_email = input(f"ZipRecruiter email [press Enter to skip]: ").strip()
    if zr_email:
        credentials["ZIPRECRUITER_EMAIL"] = zr_email
        credentials["ZIPRECRUITER_PASSWORD"] = getpass.getpass("ZipRecruiter password: ")
    print()

    # Dice (optional)
    print("--- Dice (optional) ---")
    dice_email = input(f"Dice email [press Enter to skip]: ").strip()
    if dice_email:
        credentials["DICE_EMAIL"] = dice_email
        credentials["DICE_PASSWORD"] = getpass.getpass("Dice password: ")
    print()

    # Gmail (for verification codes)
    print("--- Gmail (for verification codes) ---")
    credentials["GMAIL_EMAIL"] = input(f"Gmail email [{email}]: ").strip() or email
    print("Note: Use an app-specific password, not your regular password")
    print("      See: https://support.google.com/accounts/answer/185833")
    credentials["GMAIL_PASSWORD"] = getpass.getpass("Gmail app-specific password: ")
    print()

    # Gemini API (for job matching)
    print("--- Gemini API (optional, for job matching) ---")
    gemini_key = input("Gemini API key [press Enter to skip]: ").strip()
    if gemini_key:
        credentials["GEMINI_API_KEY"] = gemini_key
    print()

    # Write to file
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)

    creds_file = config_dir / "credentials.env"
    with open(creds_file, "w") as f:
        f.write("# MJAS Credentials - Generated by setup wizard\n")
        f.write("# DO NOT COMMIT THIS FILE - it will be encrypted\n\n")
        for key, value in credentials.items():
            if value:  # Only write non-empty values
                f.write(f"{key}={value}\n")

    # Secure the file
    os.chmod(creds_file, 0o600)

    print(f"✓ Credentials saved to: {creds_file}")
    print(f"✓ File permissions set to user-only access (600)")
    print()
    print("Next steps:")
    print("  1. Run 'python -m mjas setup' to encrypt these credentials")
    print("  2. Run 'python -m mjas list-portals' to see available portals")
    print("  3. Run 'python -m mjas run --tier 1' to start applying")
    print()


if __name__ == "__main__":
    main()
